config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "customers#index", as: "customers"
  get "/customers/alphabetized", to: "customers#alphabetized", as: "customers_alphabetized"
  get "/customers/missing_email", to: "customers#missing_email", as: "customers_missing_email"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_one_attached :image
  validates :full_name, presence: true, length: { minimum: 2 }
  validates :phone_number, presence: true
  validates :email_address, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :notes, presence: true, allow_blank: true, length: { maximum: 10000 }

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email_address", "full_name", "id", "id_value", "notes", "phone_number", "updated_at"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def alphabetized
    @customers = Customer.all.order(full_name: :asc)
  end

  def missing_email
    @customers = Customer.where(email_address: [nil, ""])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<h3><%= customer.full_name %></h3>
<div class="customer-details">
  <%= image_tag(customer.image, class: "customer-image") %>
  <div>
    <table>
      <tr>
        <th>Phone Number</th>
        <td><%= customer.phone_number %></td>
      </tr>
      <tr>
        <th>Email Address</th>
        <td><%= customer.email_address %></td>
      </tr>
      <tr>
        <th>Notes</th>
        <td><%= customer.notes %></td>
      </tr>
    </table>
  </div>
</div>

app/views/customers/alphabetized.html.erb
<h1>Customers (Alphabetized)</h1>
<%= link_to("Return to All", customers_path) %>

<ol>
  <% @customers.each do |customer| %>
    <li>
      <%= render partial: customer %>
    </li>
  <% end %>
</ol>

app/views/customers/index.html.erb
<h1>Customers</h1>
<%= link_to("Show Alphabetized", customers_alphabetized_path) %> | <%= link_to("Filter by Missing Email", customers_missing_email_path) %>

<ol>
  <% @customers.each do |customer| %>
    <li>
      <%= render partial: customer %>
    </li>
  <% end %>
</ol>

app/views/customers/missing_email.html.erb
<h1>Customers (Missing Email)</h1>
<%= link_to("Return to All", customers_path) %>

<ol>
  <% @customers.each do |customer| %>
    <li>
      <%= render partial: customer %>
    </li>
  <% end %>
</ol>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCrm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>